### ISSUE TITLE
Is there a way for a child to have multiple parents ?

### ISSUE THREAD

**Issue by Stoakes** [Yakubovich/descendant_tree#1]
Hi,

To begin with, thank you for your script, which is the best I could found.

I'd like to know if there is a way to display a child with multiple parents ? For instance to display a link between Lyanna Stark / John Snow and Eddard Stark / Jon Snow ? Thus Jon Snow would have 2 parents on the tree.

Thanks

**Comment by Yakubovich** [comment]
There is currently no way to visually display this information on the tree (I can't think of an elegant way to draw these connections), although you can represent the cycles in the JSON so that you don't have to enter the data twice.

For an example of this, see Lyarra Stark and Rickard Stark, both of whom use stark_rickard.json for their descendant tree.

**Comment by Stoakes** [comment]
Ok Thanks.
